### PR TITLE
Memory is not properly freed when removing data

### LINKED ISSUE #5: Psr\SimpleCache\CacheInterface::clear() has no effect on hasAvailableSpace()
### Bug Report

The way the Memory adapter is currently implemented (using only `memory_get_usage(true)` as source of information), calling `Psr\SimpleCache\CacheInterface::clear()` has no effect on `hasAvailableSpace()`.

Hence once a `CacheException` with previous `OutOfSpaceException` has been thrown, even calling `clear()` does not reclaim space as far as the Memory adapter is concerned. At this point the cache is permanently unusable because PHP won't ever reclaim allocated memory, only fetch more by 2 MiB increments.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

If this can't be fixed in some way, please at least document the limitation.

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes/no
| BC Break      | yes/no

### Description

As of #5, a test was provided to ensure that memory is properly freed after calling `flush`.
Thats indeed not the case.

I've played around a bit aswell as in #5 was an assumption that it might be due to the `ArrayObject` by-reference pass of the key/value in [AbstractAdapter](https://github.com/laminas/laminas-cache/blob/2.10.x/src/Storage/Adapter/AbstractAdapter.php#L758) of `laminas-cache`. I cannot confirm this as I've removed the `ArrayObject` and its still impossible to get memory freed.

I have lacks in knowledge of PHP memory handling and thus just want to provide the failing test here.
Help from the @laminas/technical-steering-committee and all others around would be highly appreciated.

Closing #5

### CODE REVIEW

**Comment by boesing** [comment]
Interesting. PHP 7.1 with min-depths is not failing here.

**Comment by Xerkus** [comment]
on a cursory glance there are 2 issues:
- looks like a bug - `memory_get_usage(true)` with `true` provides allocated memory to the process. It is not the amount that is actually used within the allocated space.
- php does not immediately collect garbage. use `gc_collect_cycles()` in catch clause in test to immediately force GC run

**Comment by boesing** [comment]
> * looks like a bug - `memory_get_usage(true)` with `true` provides allocated memory to the process. It is not the amount that is actually used within the allocated space.

Exactly. And that is the reason why we are allocating + 200 extra bytes which can be used.

> * php does not immediately collect garbage. use `gc_collect_cycles()` in catch clause in test to immediately force GC run

I've already tried that - no difference.

**Comment by Xerkus** [comment]
Then again, the problem is that system allocated memory limit might be more important than the amount of actually utilized memory for some cases. Especially if app is run in environment where exceeding allocated memory limit will get app killed.

I have no idea how php manages memory, like does it always allocate new memory and releases/reuses only once each specific page is fully used? Does it reuse partially utilized pages?

**Comment by Xerkus** [comment]
I would say if you bounce off your more or less hard limit for the memory adapter you do not want to go and allocate more memory.

that makes me inclined towards wontfix and documentation note. 

Also, do test with 4kb increments - the average page size

**Comment by boesing** [comment]
Closing in favor of #11

**Pull request closed without merging**
